[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#4ECDC4"
backgroundColor = "#1A202C"
secondaryBackgroundColor = "#2D3748"
textColor = "#FFFFFF"
font = "sans serif"
base = "dark"

[browser]
gatherUsageStats = true

[global]
developmentMode = false
